### ISSUE TITLE
Footer covers last card on mobile

### ISSUE THREAD

**Issue by DasTyp** [404-Program-not-found/404-Program-not-found.github.io#2]
Since fixed elements cover everything else you can't read the text on the last card on mobile. Tested in mobile preview on Firefox and Edge.

**Comment by DasTyp** [comment]
Solutions I can think of right now:
Set a fixed height for your footer and a margin to the bottom of your body element. Since you did not specify any height it depends on your resolution, so simply adding a margin would not work without also setting up the footer height.

Dynamically set a margin equal to the footer height. Pretty self explanatory, it's the same as above but without setting your footer height.

Make your footer apear at the bottom of the page, instead of being always visible. Also makes it prettier on mobile, since you have more viewing space!

Add a (hidden) element at the bottom of the page with the same formating as the footer, except not being fixed to your screen. Feels like a dirty solution..

**Comment by 404-Program-not-found** [comment]
I believe putting the footer at the bottom of the page should be the most cross-platform friendly approach

**Comment by 404-Program-not-found** [comment]
Problem fixed. Footer is now always at the bottom of the page!
